[program:auth]
command=/root/venvs/axegains/bin/python -um services.auth
directory=/axegains/services/
autorestart=true
startretries=3
stderr_logfile=/var/log/axegains/auth_err.log
stdout_logfile=/var/log/axegains/auth_out.log
user=root
